### ISSUE TITLE
[mips64el] fail to build buildx binary for myself

### ISSUE THREAD

**Issue by zhizunbao84** [docker/buildx#1295]
my computer is linux mips64el with 4.19.0 kernel.
i want to build buildx for myself.

docker version:
```
Client:
 Version:           19.03.0-dev
 API version:       1.40
 Go version:        go1.15.9
 Git commit:        
 Built:             Thu Dec  9 02:17:17 2021
 OS/Arch:           linux/mips64le
 Experimental:      true

Server:
 Engine:
  Version:          dev
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.15.9
  Git commit:       
  Built:            Thu Dec  9 02:10:48 2021
  OS/Arch:          linux/mips64le
  Experimental:     true
 containerd:
  Version:          c542a377
  GitCommit:        c542a377e62f5cadf1244423227059548688476c
 runc:
  Version:          1.0.0~rc6+dfsg1
  GitCommit:        1.0.0~rc6+dfsg1-3
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

docker info:
```
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., 0.0.0+unknown)

Server:
 Containers: 7
  Running: 2
  Paused: 0
  Stopped: 5
 Images: 12
 Server Version: dev
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: c542a377e62f5cadf1244423227059548688476c
 runc version: 1.0.0~rc6+dfsg1-3
 init version: fec3683
 
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://docker.mirrors.ustc.edu.cn/
  https://registry.docker-cn.com/
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No kernel memory TCP limit support
WARNING: No oom kill disable support
```

and i install tonistiigi/binfmt:
```
user@user-PC:~$ docker run --privileged --rm tonistiigi/binfmt:qemu-v6.0.0-12 --install all

user@user-PC:~$ ls -al /proc/sys/fs/binfmt_misc/
-rw-r--r-- 1 root root 0 8月   9 12:05 qemu-aarch64
-rw-r--r-- 1 root root 0 8月   9 12:05 qemu-arm
-rw-r--r-- 1 root root 0 8月   9 12:05 qemu-i386
-rw-r--r-- 1 root root 0 8月   9 12:05 qemu-mips64
-rw-r--r-- 1 root root 0 8月   9 12:05 qemu-ppc64le
-rw-r--r-- 1 root root 0 8月   9 12:05 qemu-riscv64
-rw-r--r-- 1 root root 0 8月   9 12:05 qemu-s390x
-rw-r--r-- 1 root root 0 8月   9 12:05 qemu-x86_64
```

after git clone this repo, and exec `make binaries `:
```
user@user-PC:~/buildx$ make binaries 
docker buildx bake binaries
[+] Building 2.2s (3/3) FINISHED                                                                                                         
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 32B                                                0.0s 
 => [internal] load .dockerignore                                                       0.0s 
 => => transferring context: 34B                                                       0.0s 
 => ERROR resolve image config for docker.io/docker/dockerfile:1.4                     2.2s 
------
 > resolve image config for docker.io/docker/dockerfile:1.4:
------
error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to solve
with frontend gateway.v0: no match for platform in manifest
sha256:443aab4ca21183e069e7d8b2dc68006594f40bddf1b15bbd83f5137bd93e80e2: not found
```

**Comment by crazy-max** [comment]
Same as https://github.com/tonistiigi/binfmt/issues/105#issuecomment-1214922380

`docker/dockerfile` image does not (yet) support this arch. We need first to add support for mips archs in xx project (see https://github.com/tonistiigi/xx/pull/62). When mips support is added to xx we have to push a new release of the Dockerfile frontend with these new archs.

I have pushed `crazymax/xx:mips` to add support for this arch in xx and also pushed `crazymax/dockerfile:mips` that adds support for mips archs in the meantime if you want to test on your side: https://hub.docker.com/r/crazymax/dockerfile/tags

![image](https://user-images.githubusercontent.com/1951866/187028840-df876e03-e634-4a5b-8d43-fc3b3059bd7a.png)

Then in buildx Dockerfile you have to change: https://github.com/docker/buildx/blob/1bb375fe5ccad33244bcc3ede169e1cabcc7fcc1/Dockerfile#L1

with

```dockerfile
# syntax=crazymax/dockerfile:mips
```

and: https://github.com/docker/buildx/blob/1bb375fe5ccad33244bcc3ede169e1cabcc7fcc1/Dockerfile#L10

with

```dockerfile
FROM --platform=$BUILDPLATFORM tonistiigi/xx:${XX_VERSION} AS xx
```

Then `make install` should work.

**Comment by zhizunbao84** [comment]
thank you for your respond!
according to what you say, i change the dockerfile:
```
# syntax=docker/dockerfile:1.4 
to
# syntax=crazymax/dockerfile:mips

FROM --platform=$BUILDPLATFORM tonistiigi/xx:${XX_VERSION} AS xx 
to
FROM --platform=$BUILDPLATFORM crazymax/xx:mips AS xx

also golang-1.19:alpine donot support mips, so i change it to golang:1.19-bullseye
FROM --platform=$BUILDPLATFORM golang:${GO_VERSION}-alpine AS golatest
to
FROM --platform=$BUILDPLATFORM golang:${GO_VERSION}-bullseye AS golatest
```

but when i exec `make make binaries`, i still get errors:
```
user@user-PC:~/buildx$ make binaries 
docker buildx bake binaries
[+] Building 3.7s (8/8) FINISHED                                                                                                         
 => [internal] load build definition from Dockerfile                     0.0s
 => => transferring dockerfile: 2.94kB                           0.0s 
 => [internal] load .dockerignore                           0.0s 
 => => transferring context: 34B                         0.0s 
 => resolve image config for docker.io/crazymax/dockerfile:mips                 2.2s 
 => CACHED docker-image://docker.io/crazymax/dockerfile:mips@sha256:9eda52d92cc9ec807b3f278c920e9e27e0a51bf3af85c6a36d03a22c62e90a  0.0s
 => [internal] load build definition from Dockerfile                      0.0s 
 => => transferring dockerfile: 2.94kB                           0.0s 
 => [internal] load .dockerignore                                  0.0s 
 => CANCELED [internal] load metadata for docker.io/library/golang:1.19-bullseye             1.0s 
 => ERROR [internal] load metadata for docker.io/crazymax/xx:mips               1.0s
------
 > [internal] load metadata for docker.io/crazymax/xx:mips:
------
error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: 
failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = no match for platform in manifest 
sha256:efb5816eeb39bf8573f43c7d45c34e38d7433a18a714405487fddefa689e6721: not found
```

**Comment by crazy-max** [comment]
```
error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: 
failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = no match for platform in manifest 
sha256:efb5816eeb39bf8573f43c7d45c34e38d7433a18a714405487fddefa689e6721: not found
```

Ah indeed there is an issue with `crazymax/xx:mips`. Anyway https://github.com/tonistiigi/xx/pull/62 has been merged. Can you try with:

```dockerfile
FROM --platform=$BUILDPLATFORM tonistiigi/xx:master@sha256:d4254d9739ce2de9fb88e09bdc716aa0c65f0446a2a2143399f991d71136a3d4 AS xx
```

**Comment by zhizunbao84** [comment]
@crazy-max thank you for your answer very much!!!
i change the dockerfile:
```
# syntax=docker/dockerfile:1.4 
to
# syntax=crazymax/dockerfile:mips

FROM --platform=$BUILDPLATFORM tonistiigi/xx:${XX_VERSION} AS xx 
to
FROM --platform=$BUILDPLATFORM tonistiigi/xx:master@sha256:d4254d9739ce2de9fb88e09bdc716aa0c65f0446a2a2143399f991d71136a3d4 AS xx

// golang-1.19:alpine donot support mips, so i change it to golang:1.19-bullseye
FROM --platform=$BUILDPLATFORM golang:${GO_VERSION}-alpine AS golatest
to
FROM --platform=$BUILDPLATFORM golang:${GO_VERSION}-bullseye AS golatest

// golang:1.19-bullseye already has file git, so donot need install.
delete `RUN apk add --no-cache file git` 

```

then i exec `make binaries` , it works, and generate the file `buildx` under bin/.
