### ISSUE TITLE
runc run failed: unable to start container process: /bin/sh no such file or directory

### ISSUE THREAD

**Issue by o-alquimista** [docker/buildx#1595]
Run the PHP image followed by the commands in the RUN instruction below, and it should succeed. It only fails when using buildkit.

Dockerfile (partial)
```Dockerfile
FROM php:7.4-fpm-bullseye AS php

# (...)

RUN apt-get update && apt-get install -y \
    libicu-dev \
    libzip-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
  && docker-php-ext-configure gd --with-freetype --with-jpeg \
  && docker-php-ext-install -j$(nproc) \
    gd \
    pdo_mysql \
    intl \
    zip \
    bcmath
```

Relevant build log fragment:
```
 => ERROR [php 6/8] RUN apt-get update && apt-get install -y     libicu-dev   0.3s
------
 > [php 6/8] RUN apt-get update && apt-get install -y     libicu-dev     libzip-dev     libfreetype6-dev     libjpeg62-turbo-dev     libpng-dev   && docker-php-ext-configure gd --with-freetype --with-jpeg   && docker-php-ext-install -j$(nproc)     gd     pdo_mysql     intl     zip     bcmath:
#0 0.298 runc run failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory
------
failed to solve: process "/bin/sh -c apt-get update && apt-get install -y     libicu-dev     libzip-dev     libfreetype6-dev     libjpeg62-turbo-dev     libpng-dev   && docker-php-ext-configure gd --with-freetype --with-jpeg   && docker-php-ext-install -j$(nproc)     gd     pdo_mysql     intl     zip     bcmath" did not complete successfully: exit code: 1
```

- Docker version 23.0.0, build e92dd87
- Xubuntu 22.10 kinetic on amd64

**Comment by o-alquimista** [comment]
Workaround:
```sh
sudo DOCKER_BUILDKIT=0 docker compose build
```

**Comment by MoogyG** [comment]
same here and disabling buildkit raise an error : 

```
Step 12/21 : COPY package*.json .
When using COPY with more than one source file, the destination must be a directory and end with a /
```

**Comment by sanrandry** [comment]
Did you solve it, please? 
I have this problem too

**Comment by MoogyG** [comment]
I did a system purge, i suppose that layers built from previous version of docker 23.0.0 were in an unexpected state

**Comment by sanrandry** [comment]
What did you mean by system purge, please?

**Comment by sanrandry** [comment]
I solve it by running "docker prune -a"

**Comment by rolandtritsch** [comment]
The command is `docker system prune -a`.

**Comment by o-alquimista** [comment]
> The command is `docker system prune -a`.

That works. Thanks.

**Comment by thomas-riccardi** [comment]
We got the same issue when receiving ubuntu 20.04 automatic upgrade from docker 20.10 to 23.0.0:
```#14 [builder 5/8] RUN ng lint --format=stylish
#14 0.436 runc run failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory
#14 ERROR: process "/bin/sh -c ng lint --format=stylish" did not complete successfully: exit code: 1
```

it even generated an image with missing layers:
```Dockerfile
FROM xxx as builder
...

FROM alpine:3.15 as dist
COPY --from=builder /dist /dist
```
resulted in an image with just `/dist`, not the previous alpine layers. (actual case was more complex, but we did have missing layers vs before when exploring the tar w/ docker save).

We have rolled back to 20.10 docker-ce & docker-ce-cli for now.

**Comment by neersighted** [comment]
https://github.com/moby/moby/issues/44943 looks to be the tracking issue on moby/moby. @crazy-max @tonistiigi do we want to track this on buildx, or on moby/moby?

**Comment by neersighted** [comment]
`docker builder prune -a` should be sufficient to unstick this, for anyone having problems.

**Comment by GatoSnake** [comment]
> `docker builder prune -a` should be sufficient to unstick this, for anyone having problems.

u save my life ! <3

**Comment by Karamann** [comment]
> The command is `docker system prune -a`.

it worked, thanks!!!

**Comment by ngohuytrieu** [comment]
> Workaround:
> 
> ```shell
> sudo DOCKER_BUILDKIT=0 docker compose build
> ```

I had the same issue on ubuntu and this solved it.
It worked fine but suddenly this issue occurred

**Comment by neersighted** [comment]
This issue was resolved in Moby 23.0.1.

**Comment by alqadri-prog** [comment]
it worked, thanks!!!

**Comment by jlauza** [comment]
> The command is `docker system prune -a`.

It works! Thanks mate.

**Comment by KSpakes87** [comment]
I'm having the same issue. If I run `docker system prune -a` it will just error on a different part of my build.

`ERROR: failed to solve: process "/bin/sh -c ...`

**Comment by EvanBolt** [comment]
I still face this issue on Ubuntu 22.04.  Neither `docker system prune -a` nor a full docker reinstall has fixed it.

**Comment by rfay** [comment]
Please make sure you're using current buildx and current docker. 
* https://github.com/docker/buildx/releases
* https://docs.docker.com/engine/install/ubuntu/

**Comment by EvanBolt** [comment]
I appear to be:
```
containerd.io/jammy,now 1.6.21-1 amd64 [installed]
docker-buildx-plugin/jammy,now 0.10.4-1~ubuntu.22.04~jammy amd64 [installed]
docker-ce-cli/jammy,now 5:24.0.0-1~ubuntu.22.04~jammy amd64 [installed]
docker-ce/jammy,now 5:24.0.0-1~ubuntu.22.04~jammy amd64 [installed]
docker-compose-plugin/jammy,now 2.17.3-1~ubuntu.22.04~jammy amd64 [installed]
```

**Comment by EvanBolt** [comment]
I will do some testing on a couple Ubuntu 22.04 VMs and see what if the same results occur.

**Comment by rfay** [comment]
You seem to have current. I sure recommend deleting all your images; sometimes they get corrupted. `docker rmi -f $(docker images -q)`

**Comment by EvanBolt** [comment]
Sadly, I try that as well.  So far the only things that has worked is using `DOCKER_BUILDKIT=0`

I've got a toy Dockerfile, and all I try to do is `docker run -it <image name> /bin/bash`, and I receive the error:

```
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown.
ERRO[0000] error waiting for container
```

Example Dockerfile:
```
ARG DOCKER_REGISTRY=docker.io

ARG DEBIAN_FRONTEND=noninteractive
ARG UBUNTU_VERSION=22.04

FROM ${DOCKER_REGISTRY}/ubuntu:${UBUNTU_VERSION} AS ubuntu_22_base

RUN apt-get update && apt-get install -y \
        cpp \
        gcc \
        g++
```

**Comment by EvanBolt** [comment]
That is so bizzare.

**Comment by EvanBolt** [comment]
Thank you for investigating.  It seems I have more testing to do.

**Comment by EvanBolt** [comment]
Going to leave this here for anyone else who runs into the issue.  I installed Docker Desktop on my Linux host... and now it works?

Not sure why, but I'm going to just accept it.

**Comment by enekuie** [comment]
> `docker builder prune -a` should be sufficient to unstick this, for anyone having problems.

This works but at the expense of deleting all your images in docker so if you need your other images to remain unchanged, `docker builder prune` should be a better choice

**Comment by rancid2040** [comment]
I ran into this issue as well.  I'm attempting to upgrade to the latest software, but before that, I restarted the system and the error went away.  Maybe this is something else to try for those also running into this issue.

**Comment by vncoelho** [comment]
I'm having this same issue when building our project on gitpod's containers.

**Comment by AbhijitManepatil** [comment]
I am using  `FROM node:18-alpine`
adding `WORKDIR /bin` in Dokerfile solve for me

**Comment by YarikTH** [comment]
I encountered the same problem, when installed CMake inside 22.04. At the same time, 18.04 worked just fine. I tried `docker system prune -a` and other solutions, but nothing worked.

Here is test example. It works fine on ubuntu:18.04, but fails at "rm" step on ubuntu:20.04 and later:

```
#FROM ubuntu:18.04
#FROM ubuntu:20.04
FROM ubuntu:22.04

ENV CMAKE_ARCHIVE cmake-3.23.3-linux-x86_64.sh

RUN apt-get update && \
    apt-get install -q -y \
    wget \
    file

# RUN file /bin && false

RUN wget -q --no-clobber https://cmake.org/files/v3.23/${CMAKE_ARCHIVE} && chmod 775 ./${CMAKE_ARCHIVE}
RUN ./${CMAKE_ARCHIVE} --skip-license
RUN rm -f ./${CMAKE_ARCHIVE}
```


```
 => CACHED [2/5] RUN apt-get update &&     apt-get install -q -y     wget     file                                          0.0s
 => CACHED [3/5] RUN wget -q --no-clobber https://cmake.org/files/v3.23/cmake-3.23.3-linux-x86_64.sh && chmod 775 ./cmake-  0.0s
 => CACHED [4/5] RUN ./cmake-3.23.3-linux-x86_64.sh --skip-license                                                          0.0s
 => ERROR [5/5] RUN rm -f ./cmake-3.23.3-linux-x86_64.sh                                                                    0.3s
------                                                                                                                           
 > [5/5] RUN rm -f ./cmake-3.23.3-linux-x86_64.sh:
0.239 runc run failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory
------
Dockerfile:16
--------------------
  14 |     RUN wget -q --no-clobber https://cmake.org/files/v3.23/${CMAKE_ARCHIVE} && chmod 775 ./${CMAKE_ARCHIVE}
  15 |     RUN ./${CMAKE_ARCHIVE} --skip-license
  16 | >>> RUN rm -f ./${CMAKE_ARCHIVE}
  17 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c rm -f ./${CMAKE_ARCHIVE}" did not complete successfully: exit code: 1
```

As we found out, CMake sfx installer uses "tar xf -" to unpack its content. And if it unpacked in the root directory "/", then behavior is changed. It is changed, because /bin used to be a directory in 18.04, but become a symbolic link later.

```
# 18.04
 > [3/6] RUN file /bin && false:
0.197 /bin: directory
```

```
# 22.04
 > [3/6] RUN file /bin && false:
0.238 /bin: symbolic link to usr/bin
```

Why it matters? Because CMake's tar archive also contains "/bin" directory inside. And as we found out, tar behaves differently when such name conflict occurs. If tar contains a directory "bin", while the same named directory is already there, then tar just peacefully extracts content of its "bin" directory into "bin" directory outside. But if outside is just a link, then tar replaces the link with a normal directory. So "/bin" is no longer link to the "/usr/bin", but rather a new directory with the content of tar's "bin" directory. That is unlikely has "sh" inside.

So, when `"/bin/sh": stat /bin/sh: no such file or directory` occurred then it might be not a corrupted cache problem, but actual "/bin" corruption by one of the step inside of the container.

By the way `WORKDIR /bin` also works. Kinda. Because archive is unpacked not in the "/" with corruption of the "/bin", but inside the "/bin" itself. It solves the "/bin/sh" problem, but installation is done in the wrong place.

P.S. CMake's installer has "--prefix" arg, so it should be used to install in the "/usr" or something, instead of installing in the root directory, so it is incorrect usage anyway. But it worked as intended for years and brakes only when base container was changed.

**Comment by neersighted** [comment]
This is not the same issue -- sure, you're seeing the same problem, but I think it's something of a tautology that if you tamper with `/bin`, the things you'd expect to exist there no longer exist (including things you expect implicitly, like `/bin/sh`).

I am going to close discussion on this issue for now -- none of the instances reported for the last year actually have anything to do with the original bug. If you run into this error, and you have **good reason to believe that /bin actually exists**, please open a new issue. But please do consider that is more likely than not that `/bin/sh` may really be missing.
