### ISSUE TITLE
 no active session for <id>: context deadline exceeded

### ISSUE THREAD

**Issue by errordeveloper** [docker/buildx#456]
I’m seeing buildx error like this:
```
#25 exporting to image
#25 exporting layers
#25 exporting layers 2.4s done
#25 exporting manifest sha256:bee6a0ade00b7bc2bcaae86deefc8e88e6a274dee097c8ade078e4b3a88de520 done
#25 exporting config sha256:ac3b1fe36ac072dafadc6f2aed84ff305d810a92a3e62f71a820928c832d9ac9
#25 exporting config sha256:ac3b1fe36ac072dafadc6f2aed84ff305d810a92a3e62f71a820928c832d9ac9 0.0s done
#25 exporting manifest sha256:b7812799f180bbded0a8de865efba29dcf351c858f958e506cc13e612657e4b8 0.0s done
#25 exporting config sha256:b7efbce252b10357c495758cfb1299a4c6908153eec71fc8e3097bcca5d3eb8f done
#25 exporting manifest list sha256:cbf719abf8d8c678350283152e91f9f49c1138e0087758eeaa67f6697ae4dfda done
#25 ERROR: no active session for os44n22472jqaz3bk2t3jktq2: context deadline exceeded
```

Things to note:

- buildx v0.4.2
- build takes 4h50m
- it's meant to push to quay.io
- full [build log](https://gist.github.com/errordeveloper/0151e01e1f87ec9756c321f5ab46390d)

**Comment by errordeveloper** [comment]
My first hunch is that some context is initialised with a short deadline, and that deadline expires soon since the build is taking so long.

The error is very ambiguous, however `no active session for` is quite unique and is returned from here:

https://github.com/docker/buildx/blob/fb7b670b764764dc4716df3eba07ffdae4cc47b2/vendor/github.com/moby/buildkit/session/manager.go#L176-L178

Also, `ERROR:` is a unique prefix too, perhaps somewhat surprisingly!

https://github.com/docker/buildx/blob/fb7b670b764764dc4716df3eba07ffdae4cc47b2/vendor/github.com/moby/buildkit/util/progress/progressui/printer.go#L151-L158

All I can tell is that this came from here:

https://github.com/docker/buildx/blob/fb7b670b764764dc4716df3eba07ffdae4cc47b2/util/progress/printer.go#L47-L53

I am not entirely sure where to go from here, this is seems like some kind of generic processing queue thing and this can be coming from just about anywhere in either buildkit or buildx code...

**Comment by SphtKr** [comment]
Not much to add, but seeing same behavior here today, similar setup, building multiarch across three nodes, amd64 + aarch64 + armv7l ... the arm7l one took close to eight hours and then hit this. Using plain TCP socket context to the two ARM nodes issuing the build on the amd64 node (UNIX socket).

**Comment by tonistiigi** [comment]
Was that export supposed to end with a push? What version of buildkit?

**Comment by errordeveloper** [comment]
> Was that export supposed to end with a push? What version of buildkit?

@tonistiigi yes, in my case it was.

**Comment by errordeveloper** [comment]
> Using plain TCP socket context to the two ARM nodes issuing the build on the amd64 node (UNIX socket).

In my case everything was built in the same docker instance, with qemu for some of the Arm stages.

**Comment by errordeveloper** [comment]
@tonistiigi ping!

**Comment by tonistiigi** [comment]
It looks like maybe the session connection just dropped because your build took almost 5h. You should see that from the daemon logs. If that is the case then maybe we could add logic to redial. Although not really different from build request connection itself dropping or if this happens at the same time session is being used it would still fail.

**Comment by errordeveloper** [comment]
Would you mind pointing me to where the redial logic would have to be implemented? Also, how can we improve the error message? I'm happy to have a go at fixing this one, just need some pointers. I'm pretty sure it's some sort of a drop.

**Comment by tonistiigi** [comment]
Session request happens in https://github.com/moby/buildkit/blob/master/client/solve.go#L165 but first you should figure out if it is dropping and if there is any error message of condition that causes it.

**Comment by carlonluca** [comment]
Same happens to me, very frequently. In some cases it is almost impossible to push images to docker hub. In my case I'm crossbuilding on arm to other arm versions or amd64.

```
#13 exporting to image
#13 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#13 exporting layers
#13 exporting layers 103.9s done
#13 exporting manifest sha256:eb3e1510baff02d53aa0afd867f1e4d297935fc99ee88d8152bc7cd977ba8108 0.1s done
#13 exporting config sha256:5c767564ca11f26821ce80e1fe80a713b1b0bffae5fff3e47c03cd29f295e013
#13 exporting config sha256:5c767564ca11f26821ce80e1fe80a713b1b0bffae5fff3e47c03cd29f295e013 0.1s done
#13 pushing layers
#13 pushing layers 765.1s done
#13 ERROR: no active session for mxx75rit9yyhguolxzs23e4oq: context deadline exceeded
------
 > exporting to image:
------
error: failed to solve: rpc error: code = DeadlineExceeded desc = no active session for mxx75rit9yyhguolxzs23e4oq: context deadline exceeded
```

**Comment by pgehring** [comment]
We are getting the same error while pushing to GitHub Container Registry. We though this is related to the 5GB limit of a single image layer, but we were able to push images with layersizes >5GB.
As we observed, the layers of this example are pushed succesfully according to the logfile.

```
#9 exporting to image
#9 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#9 exporting layers
#9 exporting layers 989.6s done
#9 exporting manifest sha256:78e6645f9a005842a4243947bd2e6e928f9a45b071637e2a1ba42ad9bf1c1136
#9 exporting manifest sha256:78e6645f9a005842a4243947bd2e6e928f9a45b071637e2a1ba42ad9bf1c1136 0.4s done
#9 exporting config sha256:4782358c0f8cd40619f1244a283965c470e3977ef112276f93a84eb5e5111a27
#9 exporting config sha256:4782358c0f8cd40619f1244a283965c470e3977ef112276f93a84eb5e5111a27 0.4s done
#9 pushing layers
#9 pushing layers 85.5s done
#9 ERROR: no active session for d2mw2899j00mfampt13ooz376: context deadline exceeded
------
 > exporting to image:
------
error: failed to solve: rpc error: code = DeadlineExceeded desc = no active session for d2mw2899j00mfampt13ooz376: context deadline exceeded
Error: buildx call failed with: error: failed to solve: rpc error: code = DeadlineExceeded desc = no active session for d2mw2899j00mfampt13ooz376: context deadline exceeded
```
The following log is copied from an image with layers above 5GB size. As of this log, the pushing of the manifest data fails for the example above.
```
#9 exporting to image
#9 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
#9 pushing layers 461.4s done
#9 pushing manifest for ghcr.io/...
#9 pushing manifest for ghcr.io/... 1.2s done
#9 DONE 805.3s
🛒 Extracting digest...
sha256:56e2cf1b9b5d78b293851ef6e68e23494885974db6e945141677240c458d380c
```

**Comment by errordeveloper** [comment]
https://github.com/moby/buildkit/issues/2019 is potentially related with regard implementation of underlying error handling machinery.

**Comment by deepio** [comment]
For anyone else running into this issue as part of their CI pipeline, we've decided to downgrade to legacy builds instead because reliability is more important than speed.

**Comment by hfedcba** [comment]
This also happens with short build times, in this case less than 10 minues. Often the same build passes with a build time of about 12 minutes. I'd say it fails in about 50 % of the jobs.

```
#9 DONE 528.6s
#10 exporting to image
#10 exporting layers
#10 exporting layers 10.6s done
#10 exporting manifest sha256:e341e2c0bc3510d62cc7650f3ee0e5006bb679499977832fc8a6b493d5dc8491
#10 exporting manifest sha256:e341e2c0bc3510d62cc7650f3ee0e5006bb679499977832fc8a6b493d5dc8491 0.4s done
#10 exporting config sha256:082f6382fb3047e7182df5bf0360c2cf5b9927b4b4fd8664ad058c75663bc485
#10 exporting config sha256:082f6382fb3047e7182df5bf0360c2cf5b9927b4b4fd8664ad058c75663bc485 0.4s done
#10 ERROR: no active session for 7c6uxna8fa27v8oanfq8zcj3l: context deadline exceeded
------
 > exporting to image:
------
failed to solve: rpc error: code = Unknown desc = no active session for 7c6uxna8fa27v8oanfq8zcj3l: context deadline exceeded
Cleaning up file based variables 00:00
ERROR: Job failed: exit status 1
```

**Comment by Alexander-Bartosh** [comment]
It looks like related to concurrent builds on the same instance of buildkit. 
Have the same problem reproduced multiple times. All build requests take no more than 15 minutes 
Env: 
Buildkit: moby/buildkit:v0.8.3-rootless,  Azure Kubernetes service, Azure Container service 

`error writing layer blob: no active session for s6kthksskcg47bmuu60w25p3o: context deadline exceeded`

**Comment by wojiushixiaobai** [comment]
The same problem.

**Comment by Oliveirakun** [comment]
Does anybody knows any workaround for this issue?

**Comment by wojiushixiaobai** [comment]
@Oliveirakun 
Temporary solutions can be used..
```sh
export DOCKER_BUILDKIT=1
for i in $(seq 1 3); do
  if docker buildx build --platform linux/amd64,linux/arm64 -t test:dev . --push; then
    break
  fi
  sleep 3
  if [[ "${i}" == "3" ]]; then
    echo "[Error]: build error"
    exit 1
  fi
done
```

**Comment by tonistiigi** [comment]
I'd like to see daemon debug logs for this case. Possible cases are
1) network hiccup to dial session. Solution would be to increase timeout, I think it is 5sec atm.
2) session disconnects in the middle of the build, or the session stream receives some HTTP2 error. Solution would be for client to redial.
3) something goes wrong and wrong sessionid is asked.

**Comment by ifeelingz** [comment]
Same Problem : (

**Comment by Leschge** [comment]
Same problem here ... anybody got a solution or hack for that?

**Comment by ifeelingz** [comment]
Hi everyone!

Add

`      - name: Pre Build
        run: "docker system prune -af"`

It works to me.

**Comment by Alexander-Bartosh** [comment]
Guys I have stopped seeing the problem after update to Buildkit: moby/buildkit:v0.9.0-rootless and increasing cache size from default to 50 GB ( --oci-worker-gc-keepstorage=50000)

**Comment by Alexander-Bartosh** [comment]
Still have it on Buildkit: moby/buildkit:v0.9.0-rootless, Azure Kubernetes service, Azure Container service 

6 exporting cache
#26 sha256:2700d4ef94dee473593c5c614b55b2dedcca7893909811a8f2b48291a1f581e4
#26 preparing build cache for export
#26 preparing build cache for export 0.5s done
#26 writing layer sha256:0da622ee6d9e9d6172a4eb7e3647a200f74190536a9c3b8b53a9c2d014803b7d
#26 20.95 error: no active session for aim388ulrmif949ccgd2k0xza: context deadline exceeded
#26 20.95 retrying in 1s
#26 50.95 error: no active session for aim388ulrmif949ccgd2k0xza: context deadline exceeded
#26 50.95 retrying in 2s
#26 65.96 error: no active session for aim388ulrmif949ccgd2k0xza: context deadline exceeded
#26 65.96 retrying in 4s
#26 writing layer sha256:0da622ee6d9e9d6172a4eb7e3647a200f74190536a9c3b8b53a9c2d014803b7d 75.4s done
#26 75.97 error: no active session for aim388ulrmif949ccgd2k0xza: context deadline exceeded

**Comment by wojiushixiaobai** [comment]
Still have it on Buildkit: moby/buildkit:v0.9.0-rootless, Azure Kubernetes service, Azure Container service

In my case was related to 2 concurrent cache exports:

```
## 2021-08-24T12:19:53.5930996Z #26 exporting cache
2021-08-24T12:19:53.5931582Z #26 sha256:2700d4ef94dee473593c5c614b55b2dedcca7893909811a8f2b48291a1f581e4
2021-08-24T12:19:53.5931959Z #26 preparing build cache for export
2021-08-24T12:19:54.1934009Z #26 preparing build cache for export 0.5s done
2021-08-24T12:19:54.1934497Z #26 writing layer sha256:0da622ee6d9e9d6172a4eb7e3647a200f74190536a9c3b8b53a9c2d014803b7d
2021-08-24T12:20:14.4543178Z #26 20.95 error: no active session for aim388ulrmif949ccgd2k0xza: context deadline exceeded
2021-08-24T12:20:14.4543633Z #26 20.95 retrying in 1s
2021-08-24T12:20:44.4583718Z #26 50.95 error: no active session for aim388ulrmif949ccgd2k0xza: context deadline exceeded
2021-08-24T12:20:44.4584324Z #26 50.95 retrying in 2s
2021-08-24T12:20:59.4693657Z #26 65.96 error: no active session for aim388ulrmif949ccgd2k0xza: context deadline exceeded
2021-08-24T12:20:59.4694097Z #26 65.96 retrying in 4s
2021-08-24T12:21:09.4759423Z #26 writing layer sha256:0da622ee6d9e9d6172a4eb7e3647a200f74190536a9c3b8b53a9c2d014803b7d 75.4s done
2021-08-24T12:21:09.4760392Z #26 75.97 error: no active session for aim388ulrmif949ccgd2k0xza: context deadline exceeded
2021-08-24T12:21:09.4760992Z #26 ERROR: error writing layer blob: no active session for aim388ulrmif949ccgd2k0xza: context deadline exceeded
## 2021-08-24T12:19:39.0062856Z #43 exporting cache
2021-08-24T12:19:39.0063170Z #43 sha256:2700d4ef94dee473593c5c614b55b2dedcca7893909811a8f2b48291a1f581e4
2021-08-24T12:19:39.0063480Z #43 preparing build cache for export
2021-08-24T12:19:39.4326968Z #43 preparing build cache for export 0.5s done
2021-08-24T12:19:39.5829077Z #43 writing layer sha256:0da622ee6d9e9d6172a4eb7e3647a200f74190536a9c3b8b53a9c2d014803b7d
2021-08-24T12:19:54.4506394Z #43 15.50 error: no active session for aim388ulrmif949ccgd2k0xza: context deadline exceeded
2021-08-24T12:19:54.4506870Z #43 15.50 retrying in 1s
2021-08-24T12:20:24.4557915Z #43 45.50 error: no active session for aim388ulrmif949ccgd2k0xza: context deadline exceeded
2021-08-24T12:20:24.4558485Z #43 45.50 retrying in 2s
2021-08-24T12:20:54.4602936Z #43 75.51 error: no active session for aim388ulrmif949ccgd2k0xza: context deadline exceeded
2021-08-24T12:20:54.4604240Z #43 75.51 retrying in 4s
2021-08-24T12:21:04.4717026Z #43 writing layer sha256:0da622ee6d9e9d6172a4eb7e3647a200f74190536a9c3b8b53a9c2d014803b7d 85.0s done
2021-08-24T12:21:04.4717958Z #43 85.52 error: no active session for aim388ulrmif949ccgd2k0xza: context deadline exceeded
2021-08-24T12:21:04.4718705Z #43 ERROR: error writing layer blob: no active session for aim388ulrmif949ccgd2k0xza: context deadline exceeded
```
Maybe you can format the reply so that others can read better.

**Comment by tonistiigi** [comment]
moby/buildkit#2369 was merged. Hopefully this is fixed now.

**Comment by ekaterinadimitrova2** [comment]
I had the same issue today. Yes, it is a long build but I didn't have that issue before. I did it a few times already, it popped up only today. I haven't changed my environment or anything.

**Comment by tonistiigi** [comment]
@ekaterinadimitrova2 are you running the master buildkit build with the patch?

**Comment by koehn** [comment]
I can confirm that this is still happening with the master build kit build `moby/buildkit`.

**Comment by buu700** [comment]
I've been consistently running into this with Docker for Mac 4.4.2 on my M1 MacBook Air, specifically when building a Dockerfile with a COPY instruction. Downgrading to 4.3.2 seems to have fixed the problem.

**Comment by errordeveloper** [comment]
> I've been consistently running into this with Docker for Mac 4.4.2 on my M1 MacBook Air, specifically when building a Dockerfile with a COPY instruction. Downgrading to 4.3.2 seems to have fixed the problem.

Do you use 'docker buildx create'?

**Comment by buu700** [comment]
I tried it both ways with the same result, but when I did use buildx create the command was `docker buildx create --buildkitd-flags '--oci-worker-gc --oci-worker-gc-keepstorage 50000' --name cyph_build_context ; docker buildx use cyph_build_context`. The buildkit flags were set based on @Alexander-Bartosh's suggested workaround above, and I also tried setting that in the global configuration file through the Docker for Mac preferences window.

**Comment by jamshid** [comment]
I've been trying to figure out why I get this dreaded error when doing a few concurrent `DOCKER_BUILDKIT=1 docker build(x)` builds:

`failed to solve with frontend dockerfile.v0: failed to read dockerfile: no active session for kqupcokbxys31oapli62ax81k: context deadline exceeded`

Btw I don't get the error when DOCKER_HOST is blank. Only get it when using DOCKER_HOST=ssh://docker.example.com. I'm on that server docker.example.com (passwordless ssh is configured and working).

Anyway I saw this closed bug and figure it's been fixed for so long I must have the fix, but my docker 20.10.14 on ubuntu 20 still uses `buildx: Docker Buildx (Docker Inc., v0.8.1-docker)`! Why is it so old? Is there any way to upgrade it?

**Comment by errordeveloper** [comment]
@jamshid does the error occur right away in your case or as a timeout? This was originally reported as a timeout case, if you are seeing it right away it might be a different bug altogether.

**Comment by jamshid** [comment]
@errordeveloper thanks yes its pretty immediate. 

Where are the useful logs, just `journalctl -u docker`? I can enable debug logging for docker client (--debug), server, and buildx somehow?

 I haven't had much luck narrowing it down to something easily reproducible but I can file a bug with the logs. But I'd still like to upgrade buildx to see if this is already fixed.

**Comment by errordeveloper** [comment]
> Anyway I saw this closed bug and figure it's been fixed for so long I must have the fix, but my docker 20.10.14 on ubuntu 20 still uses `buildx: Docker Buildx (Docker Inc., v0.8.1-docker)`! Why is it so old? Is there any way to upgrade it?

Are you using official Docker package for Ubuntu? I'd recommend trying using latest official packages, it's probably a good idea to also remove `~/.docker/cli-plugins/docker-buildx` before installing the latest version.

**Comment by errordeveloper** [comment]
I have to admit, what I said above is just a general point about upgrading, but having looked more specifically at the details, I can see that you don't have to upgrade.

Firstly, buildx v0.8.1 is only two weeks old and one patch relase behind latests (v0.8.2).
Secondly, this bug is most likely to be in buildkitd, and by default it's part of Docker engine. Docker 21.x is not out yet, so you won't get latest buildkit unless you use container driver.

You should try this to get an instance of buildkitd running in a container:
```
docker buildx create --use  --driver docker-container
```
Having done that, you should get latest stable version out of the box.
If you can reproduce the behaviour this way, please do open another issue as from you are saying it looks like a new bug associated with SSH transport.

**Comment by jamshid** [comment]
I _am_ using latest official ubuntu docker packages. Ok will file a new bug about the SSH transport.

**Sorry** my confusion about buildx versions was that I was looking at the _buildkit_ releases under https://github.com/moby/buildkit/releases. That versioning is apparently unrelated to the buildx cli plugin (https://github.com/docker/buildx) versioning.

**Comment by Cveinnt** [comment]
Getting this error for GitHub Action - has anyone encountered anything similar?

**Comment by aikoven** [comment]
I was getting this error in GitHub Actions. Solved by bumping action versions:

```
docker/setup-buildx-action@v2
docker/login-action@v2
docker/build-push-action@v3
```

**Comment by buu700** [comment]
> [buu700](https://github.com/buu700) commented [on Jan 24](https://github.com/docker/buildx/issues/456#issuecomment-1020790943)

> I've been consistently running into this with Docker for Mac 4.4.2 on my M1 MacBook Air, specifically when building a Dockerfile with a COPY instruction. Downgrading to 4.3.2 seems to have fixed the problem.

I confirmed that this is still an issue in version 4.9.1, this time testing on x86 macOS. As before, downgrading to 4.3.2 is an effective workaround.

**Comment by padrepitufo** [comment]
I was seeing this error crop up but only when using `v0.33.2` of tilt, having upgraded to `v0.33.10` the error went away 🤷‍♂️
